### ISSUE TITLE
Add meta preview image

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/oeth.com#35]
Currently, there's no image displayed when OETH.com is posted in Discord. Let's fix that.

<img width="835" alt="Screenshot 2023-05-16 at 10 57 13 AM" src="https://github.com/OriginProtocol/oeth.com/assets/273937/839b49b7-7d5a-45ac-883f-9736abb6c1e2">

**Comment by matt-bullock** [comment]
https://www.figma.com/file/lT360d5LvTb55hfgbRtWWT/OETH-Marketing-Site?type=design&node-id=259%3A13570&t=lsDi3TD3KHXoK9V6-1

![image](https://github.com/OriginProtocol/oeth.com/assets/39496225/22385edf-3a1f-4b94-a764-bd0a90de680c)

**Comment by micahalcorn** [comment]
This is working now for /blog but not the homepage.
